//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiBienestasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class acudiente
    {
        public int idAcudientes { get; set; }
        public string Apellidos { get; set; }
        public string NumeroDocumento { get; set; }
        public string Parentesco { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string RegistroBiometrico { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public Nullable<int> idBeneficiarios { get; set; }
        public Nullable<int> idGenero { get; set; }
        public string RegistroBiometrico1 { get; set; }
    }
}
